// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include "../inst/include/nlmixr2omegaArma.h"

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nlmixr2omegaNew
arma::vec nlmixr2omegaNew(List omeList, int diagXform);
RcppExport SEXP _nlmixr2omega_nlmixr2omegaNew(SEXP omeListSEXP, SEXP diagXformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type omeList(omeListSEXP);
    Rcpp::traits::input_parameter< int >::type diagXform(diagXformSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2omegaNew(omeList, diagXform));
    return rcpp_result_gen;
END_RCPP
}
// getTheta
NumericVector getTheta(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getTheta(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getTheta(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// setTheta
RObject setTheta(RObject inSEXP, arma::vec theta);
RcppExport SEXP _nlmixr2omega_setTheta(SEXP inSEXPSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(setTheta(inSEXP, theta));
    return rcpp_result_gen;
END_RCPP
}
// getCholOmegaInv
RObject getCholOmegaInv(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getCholOmegaInv(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getCholOmegaInv(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getOmegaInv
RObject getOmegaInv(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getOmegaInv(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getOmegaInv(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getdDomegaInv
RObject getdDomegaInv(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getdDomegaInv(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getdDomegaInv(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getCholOmega1
RObject getCholOmega1(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getCholOmega1(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getCholOmega1(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getOmegaR
RObject getOmegaR(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getOmegaR(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getOmegaR(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getCholOmega
RObject getCholOmega(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getCholOmega(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getCholOmega(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// getLogDetOMGAinv5
double getLogDetOMGAinv5(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_getLogDetOMGAinv5(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(getLogDetOMGAinv5(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
// nlmixr2omega_tr28
RObject nlmixr2omega_tr28(RObject inSEXP);
RcppExport SEXP _nlmixr2omega_nlmixr2omega_tr28(SEXP inSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type inSEXP(inSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(nlmixr2omega_tr28(inSEXP));
    return rcpp_result_gen;
END_RCPP
}
