# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlmixr2omegaNew <- function(omeList, diagXform) {
    .Call(`_nlmixr2omega_nlmixr2omegaNew`, omeList, diagXform)
}

getTheta <- function(inSEXP) {
    .Call(`_nlmixr2omega_getTheta`, inSEXP)
}

setTheta <- function(inSEXP, theta) {
    .Call(`_nlmixr2omega_setTheta`, inSEXP, theta)
}

getCholOmegaInv <- function(inSEXP) {
    .Call(`_nlmixr2omega_getCholOmegaInv`, inSEXP)
}

getOmegaInv <- function(inSEXP) {
    .Call(`_nlmixr2omega_getOmegaInv`, inSEXP)
}

getdDomegaInv <- function(inSEXP) {
    .Call(`_nlmixr2omega_getdDomegaInv`, inSEXP)
}

getCholOmega1 <- function(inSEXP) {
    .Call(`_nlmixr2omega_getCholOmega1`, inSEXP)
}

getOmegaR <- function(inSEXP) {
    .Call(`_nlmixr2omega_getOmegaR`, inSEXP)
}

getCholOmega <- function(p) {
    .Call(`_nlmixr2omega_getCholOmega`, p)
}

getLogDetOMGAinv5 <- function(p) {
    .Call(`_nlmixr2omega_getLogDetOMGAinv5`, p)
}

nlmixr2omega_tr28 <- function(p) {
    .Call(`_nlmixr2omega_nlmixr2omega_tr28`, p)
}

